// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMHpeDXfOMeqIDRBgiDTvdZkZLw_bFIB0',
    appId: '1:965768501033:web:69582fbda2aebc3a84c938',
    messagingSenderId: '965768501033',
    projectId: 'smartparkapp-4e790',
    authDomain: 'smartparkapp-4e790.firebaseapp.com',
    storageBucket: 'smartparkapp-4e790.firebasestorage.app',
    measurementId: 'G-YXTYHCTG94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvDAEzrrTWASb-xlNAX535lar_3Bi-oO4',
    appId: '1:965768501033:android:a7999d5d8c3f213d84c938',
    messagingSenderId: '965768501033',
    projectId: 'smartparkapp-4e790',
    storageBucket: 'smartparkapp-4e790.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvg-hneetI0du0wGwq-crQcwTRM_E0G2Y',
    appId: '1:965768501033:ios:98c3a598e2ecec5584c938',
    messagingSenderId: '965768501033',
    projectId: 'smartparkapp-4e790',
    storageBucket: 'smartparkapp-4e790.firebasestorage.app',
    iosBundleId: 'com.example.pathopredictApp',
  );
}
